apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: e2e-devops
data:
  NODE_ENV: "production"
  MONGO_URI: "mongodb://mongodb-service:27017/e2e-devops"
  REDIS_URL: "redis://redis-service:6379"
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "e2e-devops-bucket"
  RAZORPAY_KEY_ID: "your-razorpay-key-id"
  RAZORPAY_KEY_SECRET: "your-razorpay-key-secret"
